config/routes.rb
SimpleGallery::Application.routes.draw do

    root 'static#home'

    # Session Management
    get    '/login'  => 'sessions#new', as: :session
    post   '/login'  => 'sessions#create'
    delete '/login'  => 'sessions#destroy'
    get    '/logout' => 'sessions#destroy', as: :logout

    # Users Management
    resources :users
    get    '/register' => 'users#new', as: :register

    # Admin Namespace
    namespace :admin do
      root 'dashboard#main'

      resources :pages
      resources :settings

      resources :galleries do
        resources :images
      end

      resources :users

      get '/todo' => 'static#todo', as: :todo
      get '/about' => 'static#about'
      get '*page' => 'static#notfound', as: :notfound
    end

    # Consume Resources
    resources :artworks, only: [ :index, :show ], constraints: { format: /(json|html)/ }

    # Static Routes
    get '/md' => 'static#markdown', as: :markdown

    # Catch Pages
    get '*page' => 'static#page', as: :page

end

app/views/admin/pages/_form.html.haml
=form_for [:admin, @page] do |f|
  =f.label :title
  =f.text_field :title

  =f.label :content
  =f.text_area :content

  %h2 Other Options

  =f.label :slug
  =f.text_field :slug

  =f.submit

app/views/admin/pages/edit.html.haml
%h1 Edit Page
=render 'form'

app/views/admin/pages/index.html.haml
%h1 All Pages
%p
  Manage custom static pages here. These pages will be available to the public,
  and can contain useful information, including contact information and frequently
  requested data.

%table
  %tr
    %th Page Title
    %th URL Slug
    %th{align: 'right'}
      =link_to new_admin_page_path do
        %i.fa.fa-plus

  -Page.all.each do |p|
    %tr
      %td=p.title
      %td=link_to '/' + p.slug, '/' + p.slug
      %td{align: 'right'}
        =link_to edit_admin_page_path(p) do
          %i.fa.fa-pencil
        =link_to admin_page_path(p), method: :delete, confirm: "Really delete this page?" do
          %i.fa.fa-trash

app/views/admin/pages/new.html.haml
%h1 New Page

= render 'form'