config/routes.rb
SimpleGallery::Application.routes.draw do

    root 'static#home'

    # Session Management
    get    '/login'  => 'sessions#new', as: :session
    post   '/login'  => 'sessions#create'
    delete '/login'  => 'sessions#destroy'
    get    '/logout' => 'sessions#destroy', as: :logout

    # Users Management
    resources :users
    get    '/register' => 'users#new', as: :register

    # Admin Namespace
    namespace :admin do
      root 'dashboard#main'

      resources :pages
      resources :settings

      resources :galleries do
        resources :images
      end

      resources :users

      get '/todo' => 'static#todo', as: :todo
      get '/about' => 'static#about'
      get '*page' => 'static#notfound', as: :notfound
    end

    # Consume Resources
    resources :artworks, only: [ :index, :show ], constraints: { format: /(json|html)/ }

    # Static Routes
    get '/md' => 'static#markdown', as: :markdown

    # Catch Pages
    get '*page' => 'static#page', as: :page

end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  has_many :images, :dependent => :destroy

  def cover
    if images.empty?
      Image.new.image
    else
      images.first.image
    end
  end
end

app/controllers/admin/galleries_controller.rb
module Admin
class GalleriesController < AdminController

  before_action :get_gallery, only: [:edit, :show, :update, :destroy]

  def index
    @galleries = Gallery.all
  end

  def new
    @gallery = Gallery.new
  end

  def edit
  end

  def show
  end

  def create
    @gallery = Gallery.new(gallery_params)
    
    if @gallery.save
      redirect_to admin_galleries_path, flash: { notice: "Gallery created successfully." }
    else
      render 'new'
    end
  end

  def update
    if @gallery.update_attributes(gallery_params)
      redirect_to admin_gallery_path(@gallery), flash: { notice: "Gallery saved successfully." }
    else
      render 'edit'
    end
  end

  def destroy
    @gallery.destroy
    redirect_to admin_galleries_path, falsh: { notice: "Gallery deleted forever." }
  end

private

  def get_gallery
    @gallery = Gallery.find(params[:id])
  end

  def gallery_params
    params.require(:gallery).permit(:name, :description)
  end

end
end

app/views/admin/galleries/_form.html.haml
=form_for [:admin, @gallery] do |f|
  =f_label f, :name
  =f.text_field :name

  =f_label f, :description
  =f.text_area :description

  =f.submit

app/views/admin/galleries/edit.html.haml
-title "Edit Gallery"
-content_for :toolbar do
  =link_to admin_gallery_path(@gallery) do
    %i.fa.fa-fw.fa-ban
    Cancel

%h1 Edit Gallery
%p
  %b Note:
  This modifies only the gallery-specific settings. Please open the gallery view from the
  main menu to modify the gallery contents.

=render 'form'

app/views/admin/galleries/index.html.haml
-content_for :toolbar do
  =link_to new_admin_gallery_path do
    %i.fa.fa-fw.fa-plus
    New Gallery

-@galleries.each do |g|
  =link_to [:admin, g] do
    %div.gallery{style: "background-image: url('#{image_path g.cover}');"}
      %div.count #{g.images.count} Images
      %div.name=g.name

app/views/admin/galleries/new.html.haml
%h1 New Gallery
=render 'form'

app/views/admin/galleries/show.html.haml
-title @gallery.name
-content_for :toolbar do
  =link_to edit_admin_gallery_path(@gallery) do
    %i.fa.fa-fw.fa-pencil
    Edit Gallery
  =link_to new_admin_gallery_image_path(@gallery) do
    %i.fa.fa-fw.fa-upload
    Upload Images
  =link_to admin_gallery_path(@gallery), method: :delete, confirm: "Really delete #{@gallery.name}?" do
    %i.fa.fa-fw.fa-trash
    Delete Gallery

%h1=@gallery.name
=simple_format @gallery.description

%div#foodchain
=form_for [:admin, @gallery, Image.new(gallery: @gallery)] do |f|
  =f.hidden_field :gallery_id, value: @gallery.id

  =f.label :image, 'Drag and Drop to Upload'
  =f.file_field :image, id: "fileupload"

-@gallery.images.each do |i|
  =link_to edit_admin_gallery_image_path(@gallery, i) do
    %div.gallery{style: "background-image: url('#{image_path i.image}');"}
      %div.name=i.name

:javascript
  $(function() {
    $('#fileupload').fileupload({
      dataType: 'json',

      // Finished Callback
      done: function(e, data) {
        data.context.text("Finished.");

        $.each(data.result.files, function(index, file) {
          $('#flashes').append(
            $('<div/>').addClass('notice').text(file.name + ' uploaded OK.')
          );

          $('div#content').append(
            $('<div/>', { class: 'gallery', style: 'background-image: url(\'' + file.image_file_path + '\');' }).append(
              $('<div/>', { class: 'name', text: file.name })
            )
          );
        });
      },

      // Progress
      progress: function(e, data) {
        var progress = parseInt(data.loaded / data.total * 100, 10);
        data.context.text("Uploading (" + progress + "%)...");
      },

      // Add
      add: function(e, data) {
        data.context =
            $('<div/>').addClass('status').text("Starting upload...")

        $('<div/>')
          .addClass("image")
          .append(
            $('<div/>').addClass('filename').text(data.files[0].name)
          )
          .append(
            data.context
          )
          .appendTo($("#foodchain"));

        var jqXHR = data.submit()
          .error   (function(r,s,e) {
            $('#flashes').append(
              $('<div/>').addClass('error').text(data.files[0].name + ' could not upload.')
            );

            data.context.text(e + ": " + data.result.error);
          });
      }
    });
  });