config/routes.rb
SimpleGallery::Application.routes.draw do

    root 'static#home'

    # Session Management
    get    '/login'  => 'sessions#new', as: :session
    post   '/login'  => 'sessions#create'
    delete '/login'  => 'sessions#destroy'
    get    '/logout' => 'sessions#destroy', as: :logout

    # Users Management
    resources :users
    get    '/register' => 'users#new', as: :register

    # Admin Namespace
    namespace :admin do
      root 'dashboard#main'

      resources :pages
      resources :settings

      resources :galleries do
        resources :images
      end

      resources :users

      get '/todo' => 'static#todo', as: :todo
      get '/about' => 'static#about'
      get '*page' => 'static#notfound', as: :notfound
    end

    # Consume Resources
    resources :artworks, only: [ :index, :show ], constraints: { format: /(json|html)/ }

    # Static Routes
    get '/md' => 'static#markdown', as: :markdown

    # Catch Pages
    get '*page' => 'static#page', as: :page

end

app/views/admin/_content.html.erb
<div id="flashes">
<% flash.each do |key, val| %>
  <div class='<%= key %>'><%= val %></div>
<% end %>
</div>

<%- if content_for? :toolbar %>
<div id="toolbar">
  <%= content_for :toolbar %>
</div>
<% end %>
  
<%= render 'main' %>

app/views/admin/_main.html.haml
%div#content
  =yield

app/views/admin/_nav.html.haml
%nav
  =link_to admin_root_path, class: 'user' do
    %div.user
      %img{src: current_user.avatar.url(:thumb)}/
      %div.username=current_user.username
      %div.userrank=current_user.admin? ? "Administrator" : "User"

  %ul.accordion-nav
    -nav_menu 'Pages', 'file-text-o', 'admin/pages' do
      -nav_to 'All Pages', admin_pages_path
      -nav_to 'New Page', new_admin_page_path

    -#nav_menu 'Messages', 'envelope-o', 'admin/messages', 4 do
      -nav_to 'Inbox', admin_pages_path

    -nav_menu 'Galleries', 'image', 'admin/galleries' do
      -nav_to 'All Galleries', admin_galleries_path
      -Gallery.all.each do |g|
        -nav_to g.name, admin_gallery_path(g)
      -nav_to 'New Gallery', new_admin_gallery_path
    
    -nav_menu 'Users', 'users', 'admin/users' do
      -nav_to 'All Users', admin_users_path
      -nav_to 'Account Settings', edit_admin_user_path(current_user)
      -nav_to 'New User', new_admin_user_path

    -nav_menu 'Settings', 'cogs', 'admin/settings' do
      -nav_to 'All Settings', admin_settings_path
      -Setting.by_group.each do |g, s|
        -nav_to g, admin_settings_path(group: g)
      -nav_to 'New Setting', new_admin_setting_path
      
    -nav_to 'About', admin_about_path, 'info-circle'