config/routes.rb
SimpleGallery::Application.routes.draw do

    root 'static#home'

    # Session Management
    get    '/login'  => 'sessions#new', as: :session
    post   '/login'  => 'sessions#create'
    delete '/login'  => 'sessions#destroy'
    get    '/logout' => 'sessions#destroy', as: :logout

    # Users Management
    resources :users
    get    '/register' => 'users#new', as: :register

    # Admin Namespace
    namespace :admin do
      root 'dashboard#main'

      resources :pages
      resources :settings

      resources :galleries do
        resources :images
      end

      resources :users

      get '/todo' => 'static#todo', as: :todo
      get '/about' => 'static#about'
      get '*page' => 'static#notfound', as: :notfound
    end

    # Consume Resources
    resources :artworks, only: [ :index, :show ], constraints: { format: /(json|html)/ }

    # Static Routes
    get '/md' => 'static#markdown', as: :markdown

    # Catch Pages
    get '*page' => 'static#page', as: :page

end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :gallery

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/controllers/admin/images_controller.rb
module Admin
class ImagesController < AdminController

  before_action :get_image,   only: [:edit, :show, :update, :destroy]
  before_action :get_gallery, only: [:new, :create, :edit, :show, :update]

  def index
    @images = Image.all
  end

  def new
    @image = Image.new
  end

  def edit
  end

  def show
  end

  def create
    @image = Image.new(image_params)

    if @image.name.nil?
      @image.name = File.basename(@image.attributes['image_file_name'], '.*').humanize
    end
    
    if @image.save
      respond_to do |format|
        format.html {
          redirect_to admin_gallery_path(params[:gallery_id]), flash: { notice: "Image created successfully." }
        }
        format.json {
          render json: { status: 'OK', files: [ @image.attributes.merge({image_file_path: @image.image.url}) ] }
        }
      end
    else
      respond_to do |format|
        format.html { render 'new' }
        format.json { render json: { status: 'Error', error: nil } }
      end
    end
  end

  def update
    if @image.update_attributes(image_params)
      redirect_to admin_gallery_path(params[:gallery_id]), flash: { notice: "Image saved successfully." }
    else
      render 'edit'
    end
  end

  def destroy
    @image.destroy
    redirect_to admin_gallery_path(params[:gallery_id]), flash: { notice: "Image deleted forever." }
  end

private
  
  def get_gallery
    @gallery = Gallery.find(params[:gallery_id])
  end

  def get_image
    @image   = Image.find(params[:id])
  end

  def image_params
    params.require(:image).permit(:name, :description, :image, :gallery_id, :images)
  end

end
end

app/views/admin/images/_form.html.haml
=form_for [:admin, @gallery, @image], html: { multipart: true } do |f|
  =f.hidden_field :gallery_id, value: params[:gallery_id]

  =f_label f, :name
  =f.text_field :name

  =f_label f, :description
  =f.text_area :description

  =f_label f, :image
  =f.file_field :image

  =f.submit

app/views/admin/images/edit.html.haml
-content_for :toolbar do
  =link_to admin_gallery_path(@gallery) do
    %i.fa.fa-fw.fa-ban
    Cancel
  %i.spacer
  =link_to admin_gallery_image_path(@gallery, @image), method: :delete, confirm: "Are you sure you want to delete this image?" do
    %i.fa.fa-fw.fa-trash
    Delete Image

%h1 Edit Image

=render 'form'

app/views/admin/images/index.html.haml
-content_for :toolbar do
  =link_to new_admin_image_path do
    %i.fa.fa-fw.fa-plus
    New Image

-@images.each do |g|
  =link_to [:admin, g] do
    %div.gallery{style: "background-image: url('#{g.image.path(:medium)}');"}
      %div.name=g.name

app/views/admin/images/new.html.haml
-content_for :toolbar do
  =link_to admin_gallery_path(@gallery) do
    %i.fa.fa-fw.fa-ban
    Cancel

%h1 Upload Image
=render 'form'

app/views/admin/images/show.html.haml
=content_for :toolbar do
  =link_to edit_admin_image_path(@image) do
    %i.fa.fa-fw.fa-pencil
    Edit Image
  =link_to admin_image_path(@image), method: :delete, confirm: "Really delete #{@image.name}?" do
    %i.fa.fa-fw.fa-trash
    Delete Image

%h1=@image.name
=simple_format @image.description